### ISSUE TITLE
Create new BB: Block Quote

### ISSUE THREAD

**Issue by canterberrie** [zurb/building-blocks#100]
This is a Building Block for our upcoming News/Magazine Kit. For anyone who wants to contribute some building blocks to the site, feel free to comment below to let us know you're taking this one on!

**Description/Interaction:** A simple block quote that within a body of text. Would be great to have a left-aligned, right-aligned, and full width block quote.  Use category "media" in the YML file.

**Example:** 
<img width="490" alt="screen shot 2017-04-17 at 10 32 31 am" src="https://cloud.githubusercontent.com/assets/20821433/25097974/a2547694-235b-11e7-9e6d-cbf2d74ebb1e.png">

**Comment by IamManchanda** [comment]
@canterberrie Just on the idea 
How about nesting [blockquote](http://foundation.zurb.com/sites/docs/typography-base.html#blockquotes) into a [callout](http://foundation.zurb.com/sites/docs/callout.html) 
as similar to this => http://codepen.io/IamManchanda/pen/gWaOjP

**Comment by canterberrie** [comment]
@IamManchanda I think that's fine as long as the Building Block has the flexibility of left-aligning and right-aligning within a body of text.

**Comment by canterberrie** [comment]
@IamManchanda do you think you'll be able to knock this out today?

**Comment by IamManchanda** [comment]
@canterberrie .... You got your wish .... ohk doing it right now!
