### ISSUE TITLE
Create new BB: About the Author

### ISSUE THREAD

**Issue by canterberrie** [zurb/building-blocks#101]
This is a Building Block for our upcoming News/Magazine Kit. For anyone who wants to contribute some building blocks to the site, feel free to comment below to let us know you're taking this one on!

**Description/Interaction:** A section about the author of an article, usually found at the bottom of a news article. The Building Block should have a header, image, paragraph text, and a space for the author's social media links. 

Example:
<img width="537" alt="screen shot 2017-04-17 at 10 57 39 am" src="https://cloud.githubusercontent.com/assets/20821433/25098286/c39a78fc-235c-11e7-8f14-1438f1e5c760.png">

**Comment by IamManchanda** [comment]
PR is up #117
