### ISSUE TITLE
Magellan on how to page active state issue

### ISSUE THREAD

**Issue by rafibomb** [zurb/building-blocks#128]
Scrolling about ~ 400px past magellan destination id causes is-active class to be removed even though scrolling is still within correct section.

![5hdcfkko6i](https://cloud.githubusercontent.com/assets/5652085/25201681/716d4e86-2507-11e7-86a9-cea141074f82.gif)

**Comment by rafibomb** [comment]
Also throwing errors in console as scrolling. 909 by mid page

**Comment by kball** [comment]
I believe this is because there are many more `data-magellan-target` elements in the page than in the magellan... was your intent to add those to the nav? Or should I remove them?

**Comment by rafibomb** [comment]
That was it - thanks!
