### ISSUE TITLE
Create new BB: Wide Article Link

### ISSUE THREAD

**Issue by canterberrie** [zurb/building-blocks#130]
This is a Building Block for our upcoming News/Magazine Kit. For anyone who wants to contribute some building blocks to the site, feel free to comment below to let us know you're taking this one on!

**Description/Interaction:** A wide article link that ideally is used in a list (see example below). Should be super simple because this is meant to be a repeated item. 

**Include at least:** article name, author, short description, read more link, and thumbnail. 

Use category "media" in the YML file.

**Example taken from techcrunch.com:**
![screen shot 2017-04-20 at 10 01 49 am](https://cloud.githubusercontent.com/assets/20821433/25243002/6b0ad5be-25b0-11e7-8bdd-919dbea4c692.png)

**Comment by canterberrie** [comment]
@IamManchanda You are a rock star! Thanks man :)

**Comment by IamManchanda** [comment]
PR is up #133

-------------------------------------------------------------------------

> @IamManchanda You are a rock star! Thanks man :)

Yup i am :smiling_imp:

**Comment by rafibomb** [comment]
Closing for PR!
