### ISSUE TITLE
Create new BB: News Image Gallery

### ISSUE THREAD

**Issue by canterberrie** [zurb/building-blocks#131]
This is a Building Block for our upcoming News/Magazine Kit. For anyone who wants to contribute some building blocks to the site, feel free to assign this to yourself to let us know you're taking this one on!

**Description/Interaction:** A simple image gallery / slider that includes a short description. The Building Block doesn't have to follow the example exactly, feel free to position things however you like.

**Include at least:** Image slider, share/social links, description area.

Use "media" as category in your yml file.

Example from usatoday.com:
![screen shot 2017-04-20 at 10 09 59 am](https://cloud.githubusercontent.com/assets/20821433/25243355/9cb6d8aa-25b1-11e7-8a8b-d2dc517a89fe.png)

**Comment by IamManchanda** [comment]
Ohk will take a look this weekend... Ready to take this up... Please assign me in!!!

**Comment by canterberrie** [comment]
@IamManchanda you got it!

**Comment by canterberrie** [comment]
@IamManchanda We're aiming to get the News kit out by the end of today, do you think you'll be able to knock this one out by today? If not, feel free to assign it to me!

**Comment by IamManchanda** [comment]
@canterberrie .... ohk assigned you this one if this is urgent ....  
I will do that another one you do this :D

**Comment by canterberrie** [comment]
@IamManchanda thanks!

**Comment by IamManchanda** [comment]
If this missed the deadline and isn't urgent now I would like to take this up back!!!
Thanks @rafibomb @canterberrie

**Comment by kball** [comment]
Dang @IamManchanda do you even sleep bro? ;)

We decided to delay the actual marketing release of the new Kit to monday, and I didn't see a PR for this before end of day, so I think it's yours if you want it.

**Comment by IamManchanda** [comment]
lol ... i have a habit of sleeping 6 hours a day ..... currently in office ( saturday-half day ) ... will look to do this ... by tonight or tomm. morning! :D
