### ISSUE TITLE
Create new BB: Large Article Header

### ISSUE THREAD

**Issue by canterberrie** [zurb/building-blocks#136]
This is a Building Block for our upcoming News/Magazine Kit. For anyone who wants to contribute some building blocks to the site, feel free to assign this to yourself to let us know you're taking this one on!

**Description/Interaction:** A nice, large header section for an individual article/blog page. The idea is that this header will be at the very top of the page and provide a nice-looking, focused header for the article. Should include: a background image inside the header area, a large header (article title), publish date, author, comments. Use category "media" in yml file.

**Example:**
![screen shot 2017-04-20 at 3 00 59 pm](https://cloud.githubusercontent.com/assets/20821433/25254416/50218df4-25da-11e7-95a1-a668fc30d309.png)

**Comment by IamManchanda** [comment]
Hmmnn same like medium 
Simple but neat and clean!

Taking this up ( not because its easy but because its quite the best on the eye to read when it comes to blogs. )

**Comment by canterberrie** [comment]
@IamManchanda mind if i take this one on?

**Comment by IamManchanda** [comment]
@canterberrie .... did it and btw you look in rush?? :D

**Comment by canterberrie** [comment]
@IamManchanda yea we're trying to get the kit ready asap. You have been a huge help! Love your building blocks!

**Comment by IamManchanda** [comment]
No issue Christine!

**Comment by IamManchanda** [comment]
Closing this as added in #146
