### ISSUE TITLE
Create new BB: Simple Article Header

### ISSUE THREAD

**Issue by canterberrie** [zurb/building-blocks#137]
This is a Building Block for our upcoming News/Magazine Kit. For anyone who wants to contribute some building blocks to the site, feel free to assign this to yourself to let us know you're taking this one on!

**Description/Interaction:** A simple header area for an individual article/blog page. Should include publish date, article title, author, comment sections, social links, and an image (can be above or below text). Use category "media" in yml file.

**Example:**
![screen shot 2017-04-20 at 3 01 09 pm](https://cloud.githubusercontent.com/assets/20821433/25254497/b0130d82-25da-11e7-9379-f999c65127d7.png)

**Comment by IamManchanda** [comment]
Christine PR is up #140
