### ISSUE TITLE
Like button on building block page is automatically "liked"

### ISSUE THREAD

**Issue by canterberrie** [zurb/building-blocks#144]
Even though I haven't clicked on the "like" button for a Building Block, when I enter the page, it's already "liked".

![screen shot 2017-04-21 at 10 06 46 am](https://cloud.githubusercontent.com/assets/20821433/25288462/5f927b90-267a-11e7-89d3-c024889d35bc.png)
It looks like this even though it's my first time visiting this particular BB.

**Comment by kball** [comment]
Fixed in https://github.com/zurb/building-blocks/commit/5de83b2ddedf301c7a6928294224d83d0e328332

Deployed and tested.
