### ISSUE TITLE
[Need Help] Ran into an issue while creating a building block

### ISSUE THREAD

**Issue by IamManchanda** [zurb/building-blocks#148]
I was creating an ecommerce loading button building block 
which look to replicate this pen (bootstrap) => http://codepen.io/IamManchanda/pen/oWLyOz

Here is my codepen (foundation) => http://codepen.io/IamManchanda/pen/pPbZZv

Is there anything  i am missing here (javascript) !

cc / @kball 

------------------------------------------------------------------------------------------------

Steps to Reproduce

1. Click on Submit order button  (both pens) 
2. In first pen, this will convert into Processing order with an Loading Icon
3. In second pen, nothing happens

**Comment by IamManchanda** [comment]
I think this can be done wih [Toggler](http://foundation.zurb.com/sites/docs/toggler.html) but is it so and how to go about it ?

**Comment by kball** [comment]
the "loading"/state stuff doesn't have a true equivalent in Foundation... what you want is probably something more like this: http://foundation.zurb.com/building-blocks/blocks/button-add-cart.html or http://foundation.zurb.com/building-blocks/blocks/button-like.html

**Comment by IamManchanda** [comment]
Thanks for help kev! @kball

**Comment by IamManchanda** [comment]
Ohk @kball but one more help 
updated (but still broken) pen => http://codepen.io/IamManchanda/pen/pPbZZv

how do i call the id's dynamically for every single button that will be added to this!

```javascript
$('[data-loading-start]').click(function() {
  $(this).addClass('hide')
  $('[data-loading-end]').removeClass('hide')
});

```

**Comment by IamManchanda** [comment]
Update: sorry i didn't saved the pen ... now i saved it please check now!

**Comment by IamManchanda** [comment]
ping @kball ... awaiting reply ??

**Comment by kball** [comment]
A few ways you can do it... probably the easiest is to do it based on parent or sibling ie `$(this).parent().find('[data-loading-end]').removeClass('hide')` or `$(this).siblings('[data-loading-end]').removeClass('hide')`.

You could point from the loading start to the loading end explicitly with an id of some sort, e.g.
```
<button data-load-start="end1"></button>
<button id="end1" data-load-end</button>
```
where your js would then look something like
```
var id = $(this).data().loadStart;
$('#' + id).removeClass('hide');
```
