### ISSUE TITLE
Create New BB: Profile Card with Action Icons

### ISSUE THREAD

**Issue by canterberrie** [zurb/building-blocks#156]
This is a Building Block for our upcoming Social Media Kit. For anyone who wants to contribute some building blocks to the site, feel free to comment below to let us know you're taking this one on!

**Description/Interaction:** A profile card containing some cool info about the user. Should contain at least a profile image, name, about me section (some area for description or bite-sized info like in the sketch, this section can be repeated in the card), action icons at the bottom of the card. 

Please use category "containers" in yml file. Have fun!

**Example:**
<img width="200" alt="screen shot 2017-04-25 at 10 25 11 am" src="https://cloud.githubusercontent.com/assets/20821433/25398996/bf3e3d42-29a2-11e7-8861-a3d89030d7e2.png">

**Comment by IamManchanda** [comment]
Just co-incidentally today i did this at my work .... so no second thoughts on taking this up

**Comment by canterberrie** [comment]
@IamManchanda MVP! Thanks!

**Comment by IamManchanda** [comment]
@canterberrie Welcome christine,
but here is one thing i would like to denote .... this time i can't be urgent .... 
but will most probably complete these new requests by this week/weekend!

**Comment by IamManchanda** [comment]
PR is up #186
