### ISSUE TITLE
Create New BB: Status Update Input Box

### ISSUE THREAD

**Issue by canterberrie** [zurb/building-blocks#157]
This is a Building Block for our upcoming Social Media Kit. For anyone who wants to contribute some building blocks to the site, feel free to comment below to let us know you're taking this one on!

**Description/Interaction:** An area for the user to post a status update. Should include a textarea, some icon buttons, and a submit/post button. Feel free to vary from the sketch or add more functionality to it.

Please use category "status" in yml file. Have fun!

Example:
<img width="308" alt="screen shot 2017-04-25 at 10 25 14 am" src="https://cloud.githubusercontent.com/assets/20821433/25399332/f5ef00e6-29a3-11e7-96c5-c35e8f3ffc06.png">

**Comment by IamManchanda** [comment]
Sorry on taking up everything but i think i would love to do this so taking up this too!

**Comment by IamManchanda** [comment]
PR is up #187
