### ISSUE TITLE
Create New BB: Profile Card with Stats

### ISSUE THREAD

**Issue by canterberrie** [zurb/building-blocks#159]
This is a Building Block for our upcoming Social Media Kit. For anyone who wants to contribute some building blocks to the site, feel free to comment below to let us know you're taking this one on!

**Description/Interaction:** Another profile card, but this time with some stats. Should include at least a profile pic, name, and stats. Feel free to add more functionality to it.

Please use category "containers" in yml file. Have fun!

**Example:**
<img width="271" alt="screen shot 2017-04-25 at 10 25 31 am" src="https://cloud.githubusercontent.com/assets/20821433/25399728/2c9e75b2-29a5-11e7-940a-ac73be6e3496.png">

**Comment by IamManchanda** [comment]
If anyone is looking to take this up....
Here is a Reference => http://foundation.zurb.com/sites/docs/typography-helpers.html#statistics

Go for it !!!

**Comment by IamManchanda** [comment]
Closing this as added in #180
