### ISSUE TITLE
Create New BB: People You Might Know Section

### ISSUE THREAD

**Issue by canterberrie** [zurb/building-blocks#160]
This is a Building Block for our upcoming Social Media Kit. For anyone who wants to contribute some building blocks to the site, feel free to comment below to let us know you're taking this one on!

**Description/Interaction:** This could be a side bar or it's own section below some statuses... or something else! Feel free to vary from the sketch. Should include at least: header, profile pic & name, some kind of action button (add friend, follow, etc..). 

Please use category "containers" in yml file. Have fun!

**Example:**
<img width="209" alt="screen shot 2017-04-25 at 10 25 34 am" src="https://cloud.githubusercontent.com/assets/20821433/25399930/de3b6514-29a5-11e7-8bd4-b86694b6203c.png">

**Comment by IamManchanda** [comment]
Oh i can't hold myself up .... i want to give other's a chance .... but this one excites me as ever .... taking this up too!

**Comment by IamManchanda** [comment]
PR is up #188
