### ISSUE TITLE
Add new BB's

### ISSUE THREAD

**Issue by rafibomb** [zurb/building-blocks#185]
http://codepen.io/rafibomb/pen/eWvbYo?editors=1100
http://codepen.io/rafibomb/pen/rmmpQa?editors=1100
http://codepen.io/rafibomb/pen/OmmzZv?editors=1100
http://codepen.io/rafibomb/pen/NjjxJo?editors=1100

**Comment by IamManchanda** [comment]
Yay!

![yeti-ya](https://cloud.githubusercontent.com/assets/4970624/25561498/aa24db0e-2d8b-11e7-9f37-109cfa9c1538.png)

**Comment by rafibomb** [comment]
Lol! Done!
