### ISSUE TITLE
Topbar Responsive: Menu items misplaced by default / BB Version Support

### ISSUE THREAD

**Issue by pablopaul** [zurb/building-blocks#208]
I use `Foundation CLI version 2.2.2`.

I created a new project with "Foundation sites" via `foundation new` and used the "Zurb Template".

Then I installed the "Topbar Responsive" BB via `foundation blocks install topbar-responsive`.

Then I start to watch via `foundation watch`.

I added `{{> topbar-responsive}}` in `default.html`
```
  <body>

    {{> topbar-responsive}}
    
    {{!-- Pages you create in the src/pages/ folder are inserted here when the flattened page is created. --}}
    {{> body}}

    <script src="{{root}}assets/js/app.js"></script>
  </body>
```
Accessing `http://localhost:8001/` gives the following output with misplaced menu items:

![image](https://cloud.githubusercontent.com/assets/635526/26007316/4385cfca-3740-11e7-95bb-522187001d1b.png)

and

![image](https://cloud.githubusercontent.com/assets/635526/26007324/4f0a017c-3740-11e7-81f5-c21cf3db1894.png)

instead of (http://foundation.zurb.com/building-blocks/blocks/topbar-responsive.html)

![image](https://cloud.githubusercontent.com/assets/635526/26007394/98fc3070-3740-11e7-9041-7fc43b409458.png)

and

![image](https://cloud.githubusercontent.com/assets/635526/26007409/a57460f2-3740-11e7-9cb3-2cc20730c6a2.png)

Any idea why?

**Comment by rafibomb** [comment]
Are you using the flexbox version? This component was built with flex mode

**Comment by pablopaul** [comment]
@rafibomb all right, setting `$global-flexbox: true;` in `src/assets/scss/_settings.scss` does fix that.

Where in the according BB page can I see that the flexbox version is required?

**Comment by pablopaul** [comment]
@IamManchanda what do you mean exactly by 

> Just like version support

?

Should we open a new Issue regarding "Mention version support for all building blocks" ?

**Comment by IamManchanda** [comment]
Yup closing this and opening a new thread with the feature request would be ideal 

BTW don't forget to link this thread :D
