### ISSUE TITLE
linked images in building block not rendering 

### ISSUE THREAD

**Issue by jtalarovich** [zurb/building-blocks#209]
I've installed the Zurb template and am adding building blocks using the CLI.  I'm then trying to add the building blocks to my pages using handlebars.  for some reason, the images do not load but everything else seems to function correctly.  Any thoughts on why?

src/pages/test.html
{{>card-profile-stats}}

![screen shot 2017-05-12 at 3 36 32 pm](https://cloud.githubusercontent.com/assets/24358542/26014023/d6cdfc2a-3728-11e7-8119-f357abb904b0.png)

**Comment by jtalarovich** [comment]
another example of the problem i am describing is: fullscreen-image-slider

**Comment by IamManchanda** [comment]
Images are using sites like pixels, imgur  etc 
I think we need to fix that ?
Maybe S3 links
Poke @kball

**Comment by IamManchanda** [comment]
or maybe as internal images??

**Comment by jtalarovich** [comment]
Here’s what I’ve found, and I’ll just use this one building block as an example:  card-profile-stats

So this is what displays on your building blocks site:
http://foundation.zurb.com/building-blocks/blocks/card-profile-stats-iframe.html

<div class="card-profile-stats">
<div class="card-profile-stats-intro">
<img class="card-profile-stats-intro-pic" src="https://pbs.twimg.com/profile_images/732634911761260544/OxHbNdTF.jpg" alt="profile-image"/>
<div class="card-profile-stats-intro-content">
<h3>Joe Smith</h3>
... 

This is the code generated by the building block:

<div class="card-profile-stats">
<div class="card-profile-stats-intro">
<img class="card-profile-stats-intro-pic" style="display:none;visibility:hidden;" data-cfsrc="https://pbs.twimg.com/profile_images/732634911761260544/OxHbNdTF.jpg" alt="profile-image"/><noscript><img class="card-profile-stats-intro-pic" src="https://pbs.twimg.com/profile_images/732634911761260544/OxHbNdTF.jpg" alt="profile-image"/></noscript>
<div class="card-profile-stats-intro-content">
<h3>Joe Smith</h3>
… 

If I go in the partial and change it to the same thing as your card-profile-stats-iframe.html page, all works fine.  I’m basically just swapping out the <img> tag.  Thoughts?

**Comment by jtalarovich** [comment]
`Here’s what I’ve found, and I’ll just use this one building block as an example:  card-profile-stats

So this is what displays on your building blocks site:
http://foundation.zurb.com/building-blocks/blocks/card-profile-stats-iframe.html

<div class="card-profile-stats">
<div class="card-profile-stats-intro">
<img class="card-profile-stats-intro-pic" src="https://pbs.twimg.com/profile_images/732634911761260544/OxHbNdTF.jpg" alt="profile-image"/>
<div class="card-profile-stats-intro-content">
<h3>Joe Smith</h3>
... 

This is the code generated by the building block:

<div class="card-profile-stats">
<div class="card-profile-stats-intro">
<img class="card-profile-stats-intro-pic" style="display:none;visibility:hidden;" data-cfsrc="https://pbs.twimg.com/profile_images/732634911761260544/OxHbNdTF.jpg" alt="profile-image"/><noscript><img class="card-profile-stats-intro-pic" src="https://pbs.twimg.com/profile_images/732634911761260544/OxHbNdTF.jpg" alt="profile-image"/></noscript>
<div class="card-profile-stats-intro-content">
<h3>Joe Smith</h3>
… 

If I go in the partial and change it to the same thing as your card-profile-stats-iframe.html page, all works fine.  I’m basically just swapping out the <img> tag.  Thoughts?`

**Comment by jtalarovich** [comment]
Here’s what I’ve found, and I’ll just use this one building block as an example:  card-profile-stats

So this is what displays on your building blocks site:
http://foundation.zurb.com/building-blocks/blocks/card-profile-stats-iframe.html

`<div class="card-profile-stats">
<div class="card-profile-stats-intro">
<img class="card-profile-stats-intro-pic" src="https://pbs.twimg.com/profile_images/732634911761260544/OxHbNdTF.jpg" alt="profile-image"/>
<div class="card-profile-stats-intro-content">
<h3>Joe Smith</h3>`
...

This is the code generated by the building block:

`<div class="card-profile-stats">
<div class="card-profile-stats-intro">
<img class="card-profile-stats-intro-pic" style="display:none;visibility:hidden;" data-cfsrc="https://pbs.twimg.com/profile_images/732634911761260544/OxHbNdTF.jpg" alt="profile-image"/><noscript><img class="card-profile-stats-intro-pic" src="https://pbs.twimg.com/profile_images/732634911761260544/OxHbNdTF.jpg" alt="profile-image"/></noscript>
<div class="card-profile-stats-intro-content">
<h3>Joe Smith</h3>`
...

If I go in the partial and change it to the same thing as your card-profile-stats-iframe.html page, all works fine.  I’m basically just swapping out the <img> tag.  Thoughts?

**Comment by jtalarovich** [comment]
that's not it.  the code on http://foundation.zurb.com/building-blocks/blocks/card-profile-stats-iframe.html  is different than what the building block builds.

**Comment by jtalarovich** [comment]
![screen shot 2017-05-15 at 3 04 16 pm](https://cloud.githubusercontent.com/assets/24358542/26074436/d53feaa4-397f-11e7-997f-ec81ef4bc490.png)

**Comment by jtalarovich** [comment]
![screen shot 2017-05-15 at 3 04 24 pm](https://cloud.githubusercontent.com/assets/24358542/26074444/e10460d6-397f-11e7-82b4-07f973212ee7.png)

**Comment by jtalarovich** [comment]
If I go in the partial and change it to the same thing as your card-profile-stats-iframe.html page, all works fine.  I’m basically just swapping out the <img> tag.  Thoughts?
