### ISSUE TITLE
FLIP CARD  - THROUGH THE LOOKING GLASS (title from front card  overlays the flip card when flipped - backwards text

### ISSUE THREAD

**Issue by blynnc** [zurb/building-blocks#226]
FLIP CARD  - THROUGH THE LOOKING GLASS (title from front card  overlays the flip card when flipped - backwards text

How to reproduce this bug:
1.	Go to Foundation Building Blocks http://foundation.zurb.com/building-blocks/containers.html

2.Go to Containers > Flip Card 3. Click SEE CODE 4. You will notice that the card title in desktop mode does not beahve the same as in mobile mode.

 For example: Before clicking. ROLL TO A HOT SPOT  After clicking: Title Remains on Card and  text is displayed backwards.  Absolutely FABULOUS effect - but not quite there yet for desktop.

What should happen:
The FLIP CARD should behave same on desktop as in mobile device - the First Card Title should disappear on the Flip (Mouse Click) and not overlay the text on the flip side.

Browser(s) and Device(s) tested on: Latest version of Mac Sierra
Firefox 53.0.3

![backwards flip card desktop](https://cloud.githubusercontent.com/assets/14908417/26426491/0647b542-4096-11e7-9fcc-ba90412496ed.png)

**Comment by rafibomb** [comment]
Fixed! Interestingly firefox didn't work unless the whole container has `backface-visibility: hidden;`
https://github.com/zurb/building-blocks/commit/234db3b067a2879a5015cd358fc25d3000ffd810
