### ISSUE TITLE
Topbar Center Logo: Should the logo link to the index?

### ISSUE THREAD

**Issue by pablopaul** [zurb/building-blocks#234]
Should the logo be wrapped with a link to the site index here:
https://github.com/zurb/building-blocks/blob/master/src/building-blocks/topbar-center-logo/topbar-center-logo.html#L4

Isn´t that "best practice"? What do you think?

cc @IamManchanda

**Comment by IamManchanda** [comment]
`<a href='#"><img src="http://placehold.it/100x39" alt="" /></a>` would be better!

**Comment by pablopaul** [comment]
@IamManchanda would be a nice "first PR", do yu have such a label for contributors which contribute for the first time?
