### ISSUE TITLE
Share dropdown should have a shadow or border

### ISSUE THREAD

**Issue by tdhartwick** [zurb/building-blocks#57]
Should be differentiated visually somehow on active.

See:

<img width="121" alt="screen shot 2017-04-13 at 10 22 02 am" src="https://cloud.githubusercontent.com/assets/7873403/25016026/3c1f1940-2033-11e7-9fb7-1ae2e8929e6c.png">

**Comment by rafibomb** [comment]
Thanks @abdullahsalem for the PR! Closing in favor of https://github.com/zurb/building-blocks/pull/83
