### ISSUE TITLE
miss typing a block name will add incorrect name in app.scss

### ISSUE THREAD

**Issue by HansUXdev** [zurb/building-blocks#66]
Lets say I want to install the following
```
foundation blocks install contact-panel
```
But someone types:
```
foundation blocks install contact-anel
```

This obviously wont download anything but it will automatically add the following to you app.scss
```
@import 'components/building-blocks/contact-anel'
```
which cause throws error because that file doesn't exist.

**Comment by kball** [comment]
Nice catch, will fix

**Comment by kball** [comment]
I just published a fix for that in foundation-cli... should be fixed if you update your version of the foundation-cli to 2.2.1
