### ISSUE TITLE
Create new BB: Topbar with Responsively Hidden Links

### ISSUE THREAD

**Issue by canterberrie** [zurb/building-blocks#78]
This is a Building Block for our upcoming News/Magazine Kit. For anyone who wants to contribute some building blocks to the site, feel free to assign this to yourself to let us know you're taking this one on!

**Interaction:** A news site might have tons of categories linked in the topbar. This topbar should nest links in a dropdown as the screen gets smaller.

**Example:**
<img width="659" alt="screen shot 2017-04-14 at 4 45 01 pm" src="https://cloud.githubusercontent.com/assets/20821433/25058817/72021a58-2132-11e7-84f4-7455c9f8e0c3.png">
<img width="659" alt="gif of interaction" src="http://g.recordit.co/XAReEwOE4E.gif">

**Comment by IamManchanda** [comment]
hmmmnnn... http://codepen.io/IamManchanda/pen/ZKYwPJ
Taking this up @canterberrie @kball

**Comment by IamManchanda** [comment]
PR is up #87
