### ISSUE TITLE
Create new BB: Sticky Share Links

### ISSUE THREAD

**Issue by canterberrie** [zurb/building-blocks#79]
This is a Building Block for our upcoming News/Magazine Kit. For anyone who wants to contribute some building blocks to the site, feel free to assign this to yourself to let us know you're taking this one on!

**Description/Interaction:** A simple list of share links that will stay on the page as someone scrolls through a news article.

**Example:**
![screen shot 2017-04-14 at 4 41 39 pm](https://cloud.githubusercontent.com/assets/20821433/25058994/960493d4-2134-11e7-8843-272ec17ff9f1.png)

**Comment by IamManchanda** [comment]
I want to take this up @kball @canterberrie

**Comment by canterberrie** [comment]
@IamManchanda Go for it!

**Comment by IamManchanda** [comment]
@canterberrie .... yeah sure ... but i need one clearity .... 
do i need to just design it or also interact with the api's of social sites 
For example => https://developers.facebook.com/docs/plugins/share-button/

**Comment by canterberrie** [comment]
@IamManchanda No need to hook up the api's.

**Comment by IamManchanda** [comment]
PR is up #85!

**Comment by rafibomb** [comment]
@IamManchanda wow this is pretty awesome! Good use of Sass `@if` statements!

**Comment by IamManchanda** [comment]
@rafibomb I am a Php Guy First  .... We backend heads have Conditional's always in mind :D

**Comment by IamManchanda** [comment]
Also @rafibomb ... i am totally confused about YML thing .... so will be great if you can look into it within my PR's !
