### ISSUE TITLE
Create new BB: Hero Section with Side Links

### ISSUE THREAD

**Issue by canterberrie** [zurb/building-blocks#80]
This is a Building Block for our upcoming News/Magazine Kit. For anyone who wants to contribute some building blocks to the site, feel free to assign this to yourself to let us know you're taking this one on!

**Description/Interaction:** A hero section with a featured article on one side and article links on the other.

**Example:**
![screen shot 2017-04-14 at 5 14 46 pm](https://cloud.githubusercontent.com/assets/20821433/25059131/e58621e2-2135-11e7-924a-cd29be947204.png)

**Comment by IamManchanda** [comment]
@canterberrie Sounds kinda easy .... will wait .... for others to look into this ....
If no one will take this up .... I will go for it!

**Comment by IamManchanda** [comment]
@canterberrie .... Looked around and seems like this is already added by @abdullahsalem 

http://foundation.zurb.com/building-blocks/blocks/featured-blog-posts-panel-iframe.html
=> **Jump to Featured Posts (Grid)**

![featured-post-panel-grid](https://cloud.githubusercontent.com/assets/4970624/25070570/d7232808-22bf-11e7-8fea-dffbad7a443b.png)

**Comment by canterberrie** [comment]
@IamManchanda You're right, must have missed it! Thanks for pointing this out. Closing this PR now.

**Comment by rafibomb** [comment]
It wouldn't hurt to add this one separately and re-arrange the components. @abdullahsalem can you add this?

**Comment by rafibomb** [comment]
Oh sorry -  i see that is below. Would be good to have them as two separate ones still. Thoughts?

**Comment by IamManchanda** [comment]
> Would be good to have them as two separate ones still. Thoughts?

Yes @rafibomb

**Comment by abdullahsalem** [comment]
@rafibomb I guess that it could be within the same building-block.
@canterberrie Is it OK to reassign it to me, if you have not yet started?

**Comment by canterberrie** [comment]
@abdullahsalem I've already started on a BB for this but feel free to create a variation! Wouldn't hurt to have it in different formats. Mine will look something like this: 
![screen shot 2017-04-20 at 11 49 19 am](https://cloud.githubusercontent.com/assets/20821433/25247424/9a2bcccc-25bf-11e7-907a-95a126546e46.png)
(from usatoday.com)

**Comment by canterberrie** [comment]
@abdullahsalem There are also some other BBs that we need help building, if you feel like taking on some other ones.

**Comment by abdullahsalem** [comment]
It's OK @canterberrie! enjoy coding yours, I am already working on another BB, however I will take a look at the BBs that need help asap.
