### ISSUE TITLE
Create new BB: Small News Article Thumbnails (3-up)

### ISSUE THREAD

**Issue by canterberrie** [zurb/building-blocks#81]
This is a Building Block for our upcoming News/Magazine Kit. For anyone who wants to contribute some building blocks to the site, feel free to comment below to let us know you're taking this one on!

**Description/Interaction:** Simple article links on the homepage of a news site. Should include at least: an image, a tag, and a header. Can also include author and publish date if you want. Have fun with it!

**Example:**
<img width="665" alt="screen shot 2017-04-14 at 4 44 38 pm" src="https://cloud.githubusercontent.com/assets/20821433/25059319/28730e7c-2139-11e7-946f-b174ee3af725.png">

**Comment by IamManchanda** [comment]
@canterberrie taking this up too .... as i have made this in the past!

**Comment by canterberrie** [comment]
@IamManchanda Awesome! Appreciate it =)

**Comment by IamManchanda** [comment]
PR is up #86
