### ISSUE TITLE
Create new BB: Subscription Form

### ISSUE THREAD

**Issue by canterberrie** [zurb/building-blocks#82]
This is a Building Block for our upcoming News/Magazine Kit. For anyone who wants to contribute some building blocks to the site, feel free to comment below to let us know you're taking this one on!

**Description/Interaction:** Just a simple subscription form. Should include a header, a subheader, and an email field.

**Example:**
![screen shot 2017-04-14 at 4 41 52 pm](https://cloud.githubusercontent.com/assets/20821433/25059350/e66b6488-2139-11e7-8c18-efcd298f4367.png)

**Comment by AllyReid** [comment]
Hi,

I would like to take a look at this one. Let me know if that's cool.

**Comment by IamManchanda** [comment]
Go for it @AllyReid

**Comment by AllyReid** [comment]
added PR https://github.com/zurb/building-blocks/pull/91

**Comment by rafibomb** [comment]
@AllyReid Merged! Thanks!
